apiVersion: extensions/v1
kind: Deployment
metadata:
  name: bookshelf-frontend
  labels:
    app: bookshelf
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bookshelf
        tier: frontend
    spec:
      containers:
      - name: bookshelf-app
        image: gcr.io/[GCLOUD_PROJECT]/bookshelf
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080